baseURL = 'https://neagaru.com/'
languageCode = 'en-us'
title = 'Daniel Neagaru'
theme = "neagaru"
enableRobotsTXT = true
defaultContentLanguage = "en"

[params]
  description = "Security audits, systems automation, and time modeling – by Daniel Neagaru, penetration tester and creator of UTMS and OWASP Raider"
  author = "Daniel Neagaru"

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "about"
    weight = 1

  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    parent = "about"
    weight = 2

  [[menu.main]]
    identifier = "companies"
    name = "Companies"
    url = "/companies/"
    parent = "about"
    weight = 3

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 3

  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5
